version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DB_HOST=postgres

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react/app:/app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./nodejs:/app
    environment:
      - NODE_ENV=development
      - NODE_PORT=4000
    depends_on:
      - django

volumes:
  pgdata:
