# source 'https://rubygems.org'

# gem 'sinatra'
# gem 'pg'
# gem 'dotenv'
# gem 'em-websocket'
# gem 'em-http-server'
# gem 'mime-types', require: 'mime/types'
# gem 'json'

source 'https://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'dotenv'
gem 'em-websocket'
gem 'em-http-server'
gem 'mime-types', require: 'mime/types'
gem 'json'
