# Generated by Django 4.2.7 on 2024-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='premature_end',
            field=models.BooleanField(default=False),
        ),
    ]
