# Generated by Django 4.2.7 on 2024-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_remove_statistic_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
