# Generated by Django 4.2.7 on 2024-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_match_type_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('S', 'Single Game'), ('T', 'Tournament')], default='S', max_length=1),
        ),
    ]
