# Generated by Django 4.2.7 on 2024-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('S', 'SINGLE_GAME'), ('T', 'TOURNAMENT')], default='S', max_length=1),
        ),
    ]
