# Generated by Django 4.2.7 on 2024-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_match_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('SINGLE_GAME', 'SINGLE_GAME'), ('TOURNAMENT', 'TOURNAMENT')], default='SINGLE_GAME', max_length=20),
        ),
    ]
